version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    ports:
      - '27017:27017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  express:
    image: docker.io/bitnami/express:4
    ports:
      - '2999:2999'
    environment:
      - PORT=2999
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/myapp
      - EXPRESS_SKIP_DB_WAIT=0
      - EXPRESS_SKIP_DB_MIGRATION=0
      - EXPRESS_SKIP_NPM_INSTALL=0
      - EXPRESS_SKIP_BOWER_INSTALL=0
    volumes:
      - '../backend:/app'
    depends_on:
      - mongodb